server:
  port: 9002
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
      
      endpoint:
        shutdown:
          enabled:true
          
spring:
  application:
    name: masterdata-service
  zipkin:
    base-url: http://localhost:9411
  config:
    import: configserver:http://localhost:8888
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}

